version: '3'
services:
  discovery:
    image: discovery-app
    build:
      context: ./discovery-service/
      dockerfile: Dockerfile
    volumes:
      - /data/discovery-app
    ports:
      - 8761:8761

  config:
    image: config-app
    build:
      context: ./config-service/
      dockerfile: Dockerfile
    volumes:
      - ./config-data:/var/config-data
    depends_on:
      - discovery
    ports:
      - 9999:9999
  student-service:
    image: student-app
    build:
      context: ./student-service/
      dockerfile: Dockerfile
    volumes:
      - /data/student-app
    depends_on:
      - discovery
      - config
  administration-service:
    image: discovery-app
    build:
      context: ./administration-service/
      dockerfile: Dockerfile
    volumes:
      - /data/admin-app
    depends_on:
      - discovery
      - config
  book-service:
    image: book-app
    build:
      context: ./book-service/
      dockerfile: Dockerfile
    volumes:
      - /data/book-app
    depends_on:
      - discovery
      - config
  gateway-service:
    image: gateway-app
    build:
      context: ./api-gateway-service/
      dockerfile: Dockerfile
    volumes:
      - /data/gateway-app
    depends_on:
      - discovery
      - config
    ports:
      - 8765:8765